name: run-leetcode-tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 10

    - name: Update platform
      run: sudo apt-get update

    - name: Install dependencies
      run: sudo apt-get install ninja-build clang-tidy

    - name: Install Conan
      run: pipx install conan && conan profile detect

    - name: Run tests
      env:
        CONAN_PROFILE: conan/profile-ci
      run: ${{github.workspace}}/scripts/run-leetcode-tests.sh || exit 1
