name: run-leetcode-tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 10

    - name: Update platform
      run: sudo apt-get update

    - name: Install dependencies
      run: sudo apt-get install libgmock-dev libgtest-dev libbenchmark-dev llvm clang

    - name: Run tests
      run: run-tests.sh || exit 1
